# Generated by Django 4.1.3 on 2022-12-26 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_remove_tarea_cantidad_proveedor_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(null=True)),
                ('nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tareas.proveedor')),
            ],
        ),
    ]
