# Generated by Django 4.1.3 on 2022-12-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_remove_proveedor_cantidad_alter_proveedor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='cantidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tareas.venta'),
        ),
    ]
