# Generated by Django 4.1.3 on 2022-12-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_remove_tarea_cantidad_proveedor_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
