# Generated by Django 4.1.3 on 2022-12-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_remove_tarea_cantidad_proveedor_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='VentasPorMarca',
        ),
    ]
